/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncomePlanRouteImport } from './routes/income-plan'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWithdrawalsRouteImport } from './routes/dashboard.withdrawals'
import { Route as DashboardWithdrawRouteImport } from './routes/dashboard.withdraw'
import { Route as DashboardWeeklySalaryRouteImport } from './routes/dashboard.weekly-salary'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardVipRouteImport } from './routes/dashboard.vip'
import { Route as DashboardUplineRewardsRouteImport } from './routes/dashboard.upline-rewards'
import { Route as DashboardTransferRouteImport } from './routes/dashboard.transfer'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardTeamBonusRouteImport } from './routes/dashboard.team-bonus'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardRoiRouteImport } from './routes/dashboard.roi'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentMethodsRouteImport } from './routes/dashboard.payment-methods'
import { Route as DashboardPackagesRouteImport } from './routes/dashboard.packages'
import { Route as DashboardLevelsRouteImport } from './routes/dashboard.levels'
import { Route as DashboardInvestmentsRouteImport } from './routes/dashboard.investments'
import { Route as DashboardFavorRouteImport } from './routes/dashboard.favor'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as DashboardCheckoutDepositIdRouteImport } from './routes/dashboard.checkout.$depositId'
import { Route as DashboardAdminWithdrawalsRouteImport } from './routes/dashboard.admin.withdrawals'
import { Route as DashboardAdminWeeklySalaryRouteImport } from './routes/dashboard.admin.weekly-salary'
import { Route as DashboardAdminKycRouteImport } from './routes/dashboard.admin.kyc'
import { Route as DashboardAdminDepositsRouteImport } from './routes/dashboard.admin.deposits'
import { Route as DashboardAdminBalanceHistoryRouteImport } from './routes/dashboard.admin.balance-history'
import { Route as DashboardAdminBalanceAdjustRouteImport } from './routes/dashboard.admin.balance-adjust'
import { Route as DashboardAdminAnnouncementsRouteImport } from './routes/dashboard.admin.announcements'
import { Route as DashboardAdminUsersIndexRouteImport } from './routes/dashboard.admin.users.index'
import { Route as DashboardAdminUsersIdFavorRouteImport } from './routes/dashboard.admin.users.$id.favor'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomePlanRoute = IncomePlanRouteImport.update({
  id: '/income-plan',
  path: '/income-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWithdrawalsRoute = DashboardWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWithdrawRoute = DashboardWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeeklySalaryRoute = DashboardWeeklySalaryRouteImport.update({
  id: '/weekly-salary',
  path: '/weekly-salary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVipRoute = DashboardVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUplineRewardsRoute = DashboardUplineRewardsRouteImport.update({
  id: '/upline-rewards',
  path: '/upline-rewards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransferRoute = DashboardTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamBonusRoute = DashboardTeamBonusRouteImport.update({
  id: '/team-bonus',
  path: '/team-bonus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoiRoute = DashboardRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentMethodsRoute = DashboardPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPackagesRoute = DashboardPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLevelsRoute = DashboardLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestmentsRoute = DashboardInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavorRoute = DashboardFavorRouteImport.update({
  id: '/favor',
  path: '/favor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCheckoutDepositIdRoute =
  DashboardCheckoutDepositIdRouteImport.update({
    id: '/checkout/$depositId',
    path: '/checkout/$depositId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminWithdrawalsRoute =
  DashboardAdminWithdrawalsRouteImport.update({
    id: '/admin/withdrawals',
    path: '/admin/withdrawals',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminWeeklySalaryRoute =
  DashboardAdminWeeklySalaryRouteImport.update({
    id: '/admin/weekly-salary',
    path: '/admin/weekly-salary',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminKycRoute = DashboardAdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDepositsRoute = DashboardAdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminBalanceHistoryRoute =
  DashboardAdminBalanceHistoryRouteImport.update({
    id: '/admin/balance-history',
    path: '/admin/balance-history',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminBalanceAdjustRoute =
  DashboardAdminBalanceAdjustRouteImport.update({
    id: '/admin/balance-adjust',
    path: '/admin/balance-adjust',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminAnnouncementsRoute =
  DashboardAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersIdFavorRoute =
  DashboardAdminUsersIdFavorRouteImport.update({
    id: '/admin/users/$id/favor',
    path: '/admin/users/$id/favor',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/income-plan': typeof IncomePlanRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/favor': typeof DashboardFavorRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/levels': typeof DashboardLevelsRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roi': typeof DashboardRoiRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/team-bonus': typeof DashboardTeamBonusRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/dashboard/upline-rewards': typeof DashboardUplineRewardsRoute
  '/dashboard/vip': typeof DashboardVipRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/weekly-salary': typeof DashboardWeeklySalaryRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/balance-adjust': typeof DashboardAdminBalanceAdjustRoute
  '/dashboard/admin/balance-history': typeof DashboardAdminBalanceHistoryRoute
  '/dashboard/admin/deposits': typeof DashboardAdminDepositsRoute
  '/dashboard/admin/kyc': typeof DashboardAdminKycRoute
  '/dashboard/admin/weekly-salary': typeof DashboardAdminWeeklySalaryRoute
  '/dashboard/admin/withdrawals': typeof DashboardAdminWithdrawalsRoute
  '/dashboard/checkout/$depositId': typeof DashboardCheckoutDepositIdRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/dashboard/admin/users/$id/favor': typeof DashboardAdminUsersIdFavorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/faq': typeof FaqRoute
  '/income-plan': typeof IncomePlanRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/favor': typeof DashboardFavorRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/levels': typeof DashboardLevelsRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roi': typeof DashboardRoiRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/team-bonus': typeof DashboardTeamBonusRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/dashboard/upline-rewards': typeof DashboardUplineRewardsRoute
  '/dashboard/vip': typeof DashboardVipRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/weekly-salary': typeof DashboardWeeklySalaryRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/balance-adjust': typeof DashboardAdminBalanceAdjustRoute
  '/dashboard/admin/balance-history': typeof DashboardAdminBalanceHistoryRoute
  '/dashboard/admin/deposits': typeof DashboardAdminDepositsRoute
  '/dashboard/admin/kyc': typeof DashboardAdminKycRoute
  '/dashboard/admin/weekly-salary': typeof DashboardAdminWeeklySalaryRoute
  '/dashboard/admin/withdrawals': typeof DashboardAdminWithdrawalsRoute
  '/dashboard/checkout/$depositId': typeof DashboardCheckoutDepositIdRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersIndexRoute
  '/dashboard/admin/users/$id/favor': typeof DashboardAdminUsersIdFavorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/income-plan': typeof IncomePlanRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/favor': typeof DashboardFavorRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/levels': typeof DashboardLevelsRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roi': typeof DashboardRoiRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/team-bonus': typeof DashboardTeamBonusRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/dashboard/upline-rewards': typeof DashboardUplineRewardsRoute
  '/dashboard/vip': typeof DashboardVipRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/weekly-salary': typeof DashboardWeeklySalaryRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/balance-adjust': typeof DashboardAdminBalanceAdjustRoute
  '/dashboard/admin/balance-history': typeof DashboardAdminBalanceHistoryRoute
  '/dashboard/admin/deposits': typeof DashboardAdminDepositsRoute
  '/dashboard/admin/kyc': typeof DashboardAdminKycRoute
  '/dashboard/admin/weekly-salary': typeof DashboardAdminWeeklySalaryRoute
  '/dashboard/admin/withdrawals': typeof DashboardAdminWithdrawalsRoute
  '/dashboard/checkout/$depositId': typeof DashboardCheckoutDepositIdRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/dashboard/admin/users/$id/favor': typeof DashboardAdminUsersIdFavorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/dashboard'
    | '/faq'
    | '/income-plan'
    | '/login'
    | '/packages'
    | '/register'
    | '/vip'
    | '/dashboard/achievements'
    | '/dashboard/favor'
    | '/dashboard/investments'
    | '/dashboard/levels'
    | '/dashboard/packages'
    | '/dashboard/payment-methods'
    | '/dashboard/profile'
    | '/dashboard/roi'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/dashboard/team-bonus'
    | '/dashboard/transactions'
    | '/dashboard/transfer'
    | '/dashboard/upline-rewards'
    | '/dashboard/vip'
    | '/dashboard/wallet'
    | '/dashboard/weekly-salary'
    | '/dashboard/withdraw'
    | '/dashboard/withdrawals'
    | '/dashboard/'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/balance-adjust'
    | '/dashboard/admin/balance-history'
    | '/dashboard/admin/deposits'
    | '/dashboard/admin/kyc'
    | '/dashboard/admin/weekly-salary'
    | '/dashboard/admin/withdrawals'
    | '/dashboard/checkout/$depositId'
    | '/dashboard/admin/users/'
    | '/dashboard/admin/users/$id/favor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/faq'
    | '/income-plan'
    | '/login'
    | '/packages'
    | '/register'
    | '/vip'
    | '/dashboard/achievements'
    | '/dashboard/favor'
    | '/dashboard/investments'
    | '/dashboard/levels'
    | '/dashboard/packages'
    | '/dashboard/payment-methods'
    | '/dashboard/profile'
    | '/dashboard/roi'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/dashboard/team-bonus'
    | '/dashboard/transactions'
    | '/dashboard/transfer'
    | '/dashboard/upline-rewards'
    | '/dashboard/vip'
    | '/dashboard/wallet'
    | '/dashboard/weekly-salary'
    | '/dashboard/withdraw'
    | '/dashboard/withdrawals'
    | '/dashboard'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/balance-adjust'
    | '/dashboard/admin/balance-history'
    | '/dashboard/admin/deposits'
    | '/dashboard/admin/kyc'
    | '/dashboard/admin/weekly-salary'
    | '/dashboard/admin/withdrawals'
    | '/dashboard/checkout/$depositId'
    | '/dashboard/admin/users'
    | '/dashboard/admin/users/$id/favor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/dashboard'
    | '/faq'
    | '/income-plan'
    | '/login'
    | '/packages'
    | '/register'
    | '/vip'
    | '/dashboard/achievements'
    | '/dashboard/favor'
    | '/dashboard/investments'
    | '/dashboard/levels'
    | '/dashboard/packages'
    | '/dashboard/payment-methods'
    | '/dashboard/profile'
    | '/dashboard/roi'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/dashboard/team-bonus'
    | '/dashboard/transactions'
    | '/dashboard/transfer'
    | '/dashboard/upline-rewards'
    | '/dashboard/vip'
    | '/dashboard/wallet'
    | '/dashboard/weekly-salary'
    | '/dashboard/withdraw'
    | '/dashboard/withdrawals'
    | '/dashboard/'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/balance-adjust'
    | '/dashboard/admin/balance-history'
    | '/dashboard/admin/deposits'
    | '/dashboard/admin/kyc'
    | '/dashboard/admin/weekly-salary'
    | '/dashboard/admin/withdrawals'
    | '/dashboard/checkout/$depositId'
    | '/dashboard/admin/users/'
    | '/dashboard/admin/users/$id/favor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  IncomePlanRoute: typeof IncomePlanRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  RegisterRoute: typeof RegisterRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-plan': {
      id: '/income-plan'
      path: '/income-plan'
      fullPath: '/income-plan'
      preLoaderRoute: typeof IncomePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/withdrawals': {
      id: '/dashboard/withdrawals'
      path: '/withdrawals'
      fullPath: '/dashboard/withdrawals'
      preLoaderRoute: typeof DashboardWithdrawalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/withdraw': {
      id: '/dashboard/withdraw'
      path: '/withdraw'
      fullPath: '/dashboard/withdraw'
      preLoaderRoute: typeof DashboardWithdrawRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weekly-salary': {
      id: '/dashboard/weekly-salary'
      path: '/weekly-salary'
      fullPath: '/dashboard/weekly-salary'
      preLoaderRoute: typeof DashboardWeeklySalaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vip': {
      id: '/dashboard/vip'
      path: '/vip'
      fullPath: '/dashboard/vip'
      preLoaderRoute: typeof DashboardVipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upline-rewards': {
      id: '/dashboard/upline-rewards'
      path: '/upline-rewards'
      fullPath: '/dashboard/upline-rewards'
      preLoaderRoute: typeof DashboardUplineRewardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transfer': {
      id: '/dashboard/transfer'
      path: '/transfer'
      fullPath: '/dashboard/transfer'
      preLoaderRoute: typeof DashboardTransferRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team-bonus': {
      id: '/dashboard/team-bonus'
      path: '/team-bonus'
      fullPath: '/dashboard/team-bonus'
      preLoaderRoute: typeof DashboardTeamBonusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roi': {
      id: '/dashboard/roi'
      path: '/roi'
      fullPath: '/dashboard/roi'
      preLoaderRoute: typeof DashboardRoiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment-methods': {
      id: '/dashboard/payment-methods'
      path: '/payment-methods'
      fullPath: '/dashboard/payment-methods'
      preLoaderRoute: typeof DashboardPaymentMethodsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/packages': {
      id: '/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof DashboardPackagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/levels': {
      id: '/dashboard/levels'
      path: '/levels'
      fullPath: '/dashboard/levels'
      preLoaderRoute: typeof DashboardLevelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/investments': {
      id: '/dashboard/investments'
      path: '/investments'
      fullPath: '/dashboard/investments'
      preLoaderRoute: typeof DashboardInvestmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favor': {
      id: '/dashboard/favor'
      path: '/favor'
      fullPath: '/dashboard/favor'
      preLoaderRoute: typeof DashboardFavorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/checkout/$depositId': {
      id: '/dashboard/checkout/$depositId'
      path: '/checkout/$depositId'
      fullPath: '/dashboard/checkout/$depositId'
      preLoaderRoute: typeof DashboardCheckoutDepositIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/withdrawals': {
      id: '/dashboard/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/dashboard/admin/withdrawals'
      preLoaderRoute: typeof DashboardAdminWithdrawalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/weekly-salary': {
      id: '/dashboard/admin/weekly-salary'
      path: '/admin/weekly-salary'
      fullPath: '/dashboard/admin/weekly-salary'
      preLoaderRoute: typeof DashboardAdminWeeklySalaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/kyc': {
      id: '/dashboard/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/dashboard/admin/kyc'
      preLoaderRoute: typeof DashboardAdminKycRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/deposits': {
      id: '/dashboard/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/dashboard/admin/deposits'
      preLoaderRoute: typeof DashboardAdminDepositsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/balance-history': {
      id: '/dashboard/admin/balance-history'
      path: '/admin/balance-history'
      fullPath: '/dashboard/admin/balance-history'
      preLoaderRoute: typeof DashboardAdminBalanceHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/balance-adjust': {
      id: '/dashboard/admin/balance-adjust'
      path: '/admin/balance-adjust'
      fullPath: '/dashboard/admin/balance-adjust'
      preLoaderRoute: typeof DashboardAdminBalanceAdjustRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/announcements': {
      id: '/dashboard/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/dashboard/admin/announcements'
      preLoaderRoute: typeof DashboardAdminAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users/': {
      id: '/dashboard/admin/users/'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users/'
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users/$id/favor': {
      id: '/dashboard/admin/users/$id/favor'
      path: '/admin/users/$id/favor'
      fullPath: '/dashboard/admin/users/$id/favor'
      preLoaderRoute: typeof DashboardAdminUsersIdFavorRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardFavorRoute: typeof DashboardFavorRoute
  DashboardInvestmentsRoute: typeof DashboardInvestmentsRoute
  DashboardLevelsRoute: typeof DashboardLevelsRoute
  DashboardPackagesRoute: typeof DashboardPackagesRoute
  DashboardPaymentMethodsRoute: typeof DashboardPaymentMethodsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRoiRoute: typeof DashboardRoiRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTeamBonusRoute: typeof DashboardTeamBonusRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardTransferRoute: typeof DashboardTransferRoute
  DashboardUplineRewardsRoute: typeof DashboardUplineRewardsRoute
  DashboardVipRoute: typeof DashboardVipRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardWeeklySalaryRoute: typeof DashboardWeeklySalaryRoute
  DashboardWithdrawRoute: typeof DashboardWithdrawRoute
  DashboardWithdrawalsRoute: typeof DashboardWithdrawalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminAnnouncementsRoute: typeof DashboardAdminAnnouncementsRoute
  DashboardAdminBalanceAdjustRoute: typeof DashboardAdminBalanceAdjustRoute
  DashboardAdminBalanceHistoryRoute: typeof DashboardAdminBalanceHistoryRoute
  DashboardAdminDepositsRoute: typeof DashboardAdminDepositsRoute
  DashboardAdminKycRoute: typeof DashboardAdminKycRoute
  DashboardAdminWeeklySalaryRoute: typeof DashboardAdminWeeklySalaryRoute
  DashboardAdminWithdrawalsRoute: typeof DashboardAdminWithdrawalsRoute
  DashboardCheckoutDepositIdRoute: typeof DashboardCheckoutDepositIdRoute
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute
  DashboardAdminUsersIdFavorRoute: typeof DashboardAdminUsersIdFavorRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardFavorRoute: DashboardFavorRoute,
  DashboardInvestmentsRoute: DashboardInvestmentsRoute,
  DashboardLevelsRoute: DashboardLevelsRoute,
  DashboardPackagesRoute: DashboardPackagesRoute,
  DashboardPaymentMethodsRoute: DashboardPaymentMethodsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRoiRoute: DashboardRoiRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTeamBonusRoute: DashboardTeamBonusRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardTransferRoute: DashboardTransferRoute,
  DashboardUplineRewardsRoute: DashboardUplineRewardsRoute,
  DashboardVipRoute: DashboardVipRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardWeeklySalaryRoute: DashboardWeeklySalaryRoute,
  DashboardWithdrawRoute: DashboardWithdrawRoute,
  DashboardWithdrawalsRoute: DashboardWithdrawalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminAnnouncementsRoute: DashboardAdminAnnouncementsRoute,
  DashboardAdminBalanceAdjustRoute: DashboardAdminBalanceAdjustRoute,
  DashboardAdminBalanceHistoryRoute: DashboardAdminBalanceHistoryRoute,
  DashboardAdminDepositsRoute: DashboardAdminDepositsRoute,
  DashboardAdminKycRoute: DashboardAdminKycRoute,
  DashboardAdminWeeklySalaryRoute: DashboardAdminWeeklySalaryRoute,
  DashboardAdminWithdrawalsRoute: DashboardAdminWithdrawalsRoute,
  DashboardCheckoutDepositIdRoute: DashboardCheckoutDepositIdRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
  DashboardAdminUsersIdFavorRoute: DashboardAdminUsersIdFavorRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  IncomePlanRoute: IncomePlanRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  RegisterRoute: RegisterRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
